export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
export const GET_ALL_QUESTION_TYPES = 'GET_ALL_QUESTION_TYPES';
export const SUBMIT_QUESTION = 'SUBMIT_QUESTION';
export const QUESTION_ERROR = 'SUBMIT_QUESTION_ERROR';
