export const QUESTION_TYPES = ['MULTIPLE_CHOICE', 'TEXT'];
export const QUESTION_CATEGORIES = [
  'TRASH',
  'ART & CULTURE',
  'BIOLOGY',
  'ECONOMY',
  'FILM & TV',
  'FOOD & DRINKS',
  'LITERATURE',
  'LANGUAGE',
  'POLITICS',
  'HISTORY',
  'MUSIC',
  'SPORT',
  'GEOGRAPHY',
  'SCIENCE',
  'MISCELLANEOUS',
];
